<a href="https://colab.research.google.com/github/vaibhavkale2007/DataScience-SE24/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("The 3x3 matrix is:")
print(matrix)


determinant = np.linalg.det(matrix)

print(f"\nThe determinant of the matrix is: {determinant}")

The 3x3 matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The determinant of the matrix is: 0.0


In [ ]:
import numpy as np


invertible_matrix = np.array([[1, 2, 3],
                            [0, 1, 4],
                            [5, 6, 0]])

print("The invertible matrix is:")
print(invertible_matrix)

determinant_invertible = np.linalg.det(invertible_matrix)
print(f"\nThe determinant of the invertible matrix is: {determinant_invertible}")


inverse_matrix = np.linalg.inv(invertible_matrix)

print("\nThe inverse of the matrix is:")
print(inverse_matrix)

The invertible matrix is:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

The determinant of the invertible matrix is: 0.9999999999999964

The inverse of the matrix is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
import numpy as np


A = np.array([[2, 3],
              [4, 5]])


B = np.array([10, 20])

print("Coefficient Matrix A:")
print(A)
print("\nConstant Vector B:")
print(B)


solution = np.linalg.solve(A, B)

print("\nThe solution for [x, y] is:")
print(solution)

x = solution[0]
y = solution[1]
print(f"\nTherefore, x = {x} and y = {y}")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constant Vector B:
[10 20]

The solution for [x, y] is:
[5. 0.]

Therefore, x = 5.0 and y = 0.0
