<a href="https://colab.research.google.com/github/vaibhavkale2007/DataScience-SE24/blob/main/SimpleOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

# Example usage:
number = 5
print(f"The factorial of {number} is {factorial(number)}")

The factorial of 5 is 120


In [2]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("The 3x3 matrix is:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)

print(f"\nThe determinant of the matrix is: {determinant}")

The 3x3 matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The determinant of the matrix is: 0.0


In [3]:
import numpy as np

# Define an invertible 3x3 matrix
invertible_matrix = np.array([[1, 2, 3],
                            [0, 1, 4],
                            [5, 6, 0]])

print("The invertible matrix is:")
print(invertible_matrix)

# Compute the determinant of the invertible matrix to confirm it's non-zero
determinant_invertible = np.linalg.det(invertible_matrix)
print(f"\nThe determinant of the invertible matrix is: {determinant_invertible}")

# Compute the inverse
inverse_matrix = np.linalg.inv(invertible_matrix)

print("\nThe inverse of the matrix is:")
print(inverse_matrix)

The invertible matrix is:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

The determinant of the invertible matrix is: 0.9999999999999964

The inverse of the matrix is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
